#tier 1 nepali cities
tier_1_cities = [
    "Kathmandu",
    "Lalitpur",
    "Bhaktapur",
    "Pokhara",
    "Biratnagar",
    "Birgunj",
    "Bharatpur",
    "Dharan",
    "Hetauda",
    "Butwal"
]
# top 50 nepali tier 2 cities 
tier_2_cities = [
    "Janakpur",
    "Dhangadhi",
    "Tulsipur",
    "Itahari",
    "Birtamod",
    "Nepalgunj",
    "Damak",
    "Ghorahi",
    "Mechinagar",
    "Bhimeshwor",
    "Gulariya",
    "Rajbiraj",
    "Birendranagar",
    "Kirtipur",
    "Dipayal Silgadhi",
    "Lamki Chuha",
    "Tansen",
    "Bhimdatta",
    "Malangwa",
    "Jaleshwar",
    "Siddharthanagar (Bhairahawa)",
    "Banepa",
    "Panauti",
    "Dullu",
    "Ramechhap",
    "Chandragiri Municipality",
    "Madhyapur Thimi Municipality",
    "Kavrepalanchok",
    "Darchula",
    "Dadeldhura",
    "Bajhang",
    "Bajura",
    "Achham",
    "Doti",
    "Kailali",
    "Kanchanpur",
    "Rukum",
    "Rolpa",
    "Salyan",
    "Pyuthan",
    "Dang",
    "Banke",
    "Bardiya",
    "Surkhet",
    "Dailekh",
    "Jumla",
    "Dolpa",
    "Humla",
    "Mugu",
    "Manang",
    "Mustang",
    "Rasuwa",
    "Sindhupalchok",
    "Dolakha",
    "Ramechhap",
    "Sindhuli",
    "Okhaldhunga",
    "Solukhumbu",
]
